v = input('Digite algo. ')
t = type(v)
print('{} é do tipo {}' .format(v, t))
print('{} é numérico? '.format(v), v.isnumeric())
print('{} é alfabético? '.format(v), v.isalpha())
print('{} é alfanumérico? ' .format(v), v.isalnum())
print('{} está escrito com letras minúsculas? ' .format(v), v.islower())
print('{} está escrito em letras maiúsculas? ' .format(v), v.isupper())
print('{} tem a primeira letra maiúscula? ' .format(v), v.istitle())
print('{} tem espaços? '.format(v), v.isspace())